//min h max h h -scren lere bax
//MOBIL UCUN MEDIA QUERY VE EGER 1536PX SONRA DIZAYN POZULSA MEDIAQ QUERY
//https://www.figma.com/design/EWmzcVkd7qbP5Nf7iMvuqP/Trafalgar-Landing-Page?node-id=0-1&p=f&t=eJxBvk7ohTMIltbQ-0

//MEN KOD UCUN BAXDIGIN DIZAYN ARALIGI-640PX ILE 1536PX




//bunu arasdir ve button var idi oaradki focus ve navbari

//divin ozunu ve classname de global et buradaaaa

//isdeki gride de bax ki buradki gridi duzeldesen

//grid tam olaraq responsiv deyil


// https://websitedemos.net/multimed-04/?customize=template



//Hostpiral sira gozleme progrmai
//cofee shop (gloria progrmia)
//isleri bolusdmdurme progmai yaz


//location navigate Link ferqi


//All hash-e normal ad qoy


//hash ile route ferqi hashde sehife deyisri?? a