//min h max h h -scren lere bax
//MOBIL UCUN MEDIA QUERY VE EGER 1536PX SONRA DIZAYN POZULSA MEDIAQ QUERY
//https://www.figma.com/design/EWmzcVkd7qbP5Nf7iMvuqP/Trafalgar-Landing-Page?node-id=0-1&p=f&t=eJxBvk7ohTMIltbQ-0

//MEN KOD UCUN BAXDIGIN DIZAYN ARALIGI-640PX ILE 1536PX


//dizayn responsivlik eni 1024pxden sonra edilib evveli yox



//bunu arasdir ve button var idi oaradki focus ve navbari

//divin ozunu ve classname de global et buradaaaa

//isdeki gride de bax ki buradki gridi duzeldesen

//grid tam olaraq responsiv deyil


// https://websitedemos.net/multimed-04/?customize=template
//https://www.youtube.com/watch?v=9aaZUSdA2g0&list=PLImJ3umGjxdBzMlTvJk1iz3qFyJhl28S5&index=8


//Hostpiral sira gozleme progrmai
//cofee shop (gloria progrmia)
//isleri bolusdmdurme progmai yaz


//location navigate Link ferqi


//All hash-e normal ad qoy


//hash ile route ferqi hashde sehife deyisri?? a linki

//navbari duzelt


//https://preview.themeforest.net/item/pharmez-online-pharmacy-html-template/full_screen_preview/59980262



// https://www.youtube.com/watch?v=XJSOgV4VELk slider

//https://www.youtube.com/watch?v=wIyHSOugGGw

//https://www.youtube.com/watch?v=gmI5nvzv170


//https://www.youtube.com/watch?v=tEGapA8iEkE








///consulutin jsserver jsx ve department jsxde logic kodlari bax ve adlainr deyis
///ve hemciunn useQuery useMutation ,vm islet mutleq


//https://chatgpt.com/c/6904b84c-46e4-8329-9385-cee8b775f402 iki useffect qaydasi


// department mentiqindde problem var duzelt(logicde)


//consultaionda ve digerlerinde responsivliye bax

// npx json-server --watch src/MockBackend/db.json --port 3031





// 👉 Ən çox istifadə olunan:
// 🔹 1366 × 768 — Dünyada ən populyar laptop ölçüsü ✅

// Digərləri:

// 1280 × 800   (MacBook Air köhnə modellər)
// 1440 × 900   (HD+ noutbuklar)
// 1600 × 900   (orta səviyyə noutbuk)
// 1920 × 1080  (Full HD laptop)--------------menim laptop



// 🖥️ Masaüstü (Desktop)

// 👉 Ən çox istifadə olunan:
// 🔹 1920 × 1080 (Full HD) — Ən yayılmış masaüstü ölçü ✅

// Digərləri:

// 1280 × 1024   (köhnə ofis monitorları)
// 1440 × 900    (HD+ monitor)
// 1536 × 864    (orta ölçülü ekran)
// 1600 × 900    (HD+ ekran)
// 1680 × 1050   (WSXGA+)
// 1920 × 1200   (Full HD+)
// 2048 × 1080   (Cinema genişlik)
// 2560 × 1080   (UltraWide Full HD)
// 2560 × 1440   (2K / QHD monitor)--------------evdeki komp
// 2880 × 1800   (MacBook Pro Retina)
// 3000 × 2000   (Surface Studio)
// 3440 × 1440   (UltraWide 2K)
// 3840 × 2160   (4K monitor)
// 5120 × 2880   (5K monitor)
// 6016 × 3384   (6K Apple Pro Display XDR)
// 7680 × 4320   (8K monitor)

// 🧭 Qısa test üçün yetərli əsas ölçülər (praktiki variant)