   export const departments = [
      {
        id: 1,
        title: "Cardiology",
        img: "/images/departments/Heart.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "/services/doctor/cardiology",
      },
      {
        id: 2,
        title: "Ophthalmology",
        img: "/images/departments/Eye.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 3,
        title: "Pulmonary",
        img: "/images/departments/Pulmonary.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 4,
        title: "Dental",
        img: "/images/departments/Dental.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 5,
        title: "Diagnostics",
        img: "/images/Diagnostics.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 6,
        title: "For disabled",
        img: "/images/For disabled.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 7,
        title: "Traumotoligy",
        img: "/images/Traumotoligy.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
      {
        id: 8,
        title: "Laboratory",
        img: "/images/Laboratory.png",
        width: "w-[65px]",
        height: "h-[55px]",
        Link: "services/doctor",
      },
    ];
 